### ISSUE TITLE
Label Management is broken / Fix in progress

### ISSUE THREAD

**Issue by webcracy** [nu7hatch/gmail#104]
[Updated April 21, 2014]

Discussion in Issue #73 and PR #102 hinted at a problem with label management methods in the `Gmail::Message` class. After a more detailed look, it is confirmed that several parts of it are broken and are currently being fixed.

To sum up:
* Archiving is actually broken, although might appear OK to most users
* Moving any message to a folder is actually broken, as all end up in trash
* Adding and removing labels are broken and are being fixed

I'm doing this work on https://github.com/webcracy/gmail/tree/label_mgt building on PR #102

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#104
