### ISSUE TITLE
Git usage guidelines...

### ISSUE THREAD

**Issue by jgrevich** [nu7hatch/gmail#106]
I am a big fan of the following in regards to the usage of git:

* Use Gitflow - http://nvie.com/posts/a-successful-git-branching-model/
* Commit messages - http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message https://wiki.openstack.org/wiki/GitCommitMessages , http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html, and http://ablogaboutcode.com/2011/03/23/proper-git-commit-messages-and-an-elegant-git-history/
* Minimal config for git account - https://help.github.com/articles/setting-your-email-in-git

Please post your thoughts on the above as I hope for us to adhere to these guidelines going forward.  The Diaspora project also has a nice developer guide that we can refer to: https://wiki.diasporafoundation.org/Getting_started_with_contributing

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#106
