### ISSUE TITLE
Issue with Rails 4.1

### ISSUE THREAD

**Issue by tomrossi7** [nu7hatch/gmail#113]
Unable to install with Rails 4.1:

Bundler could not find compatible versions for gem "mail":
  In Gemfile:
    rails (= 4.1.0) ruby depends on
      actionmailer (= 4.1.0) ruby depends on
        mail (~> 2.5.4) ruby

    gmail (>= 0) ruby depends on
      mail (2.5.3)

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#113
