### ISSUE TITLE
LoadError: cannot load such file -- mime/message

### ISSUE THREAD

**Issue by kosherfrog** [nu7hatch/gmail#118]
Running from irb, I get connected. Then when doing a search as the following one
gmail.inbox.count(:unread, :from => "username") or any other search I consistently get the following error: LoadError: cannot load such file -- mime/message followed by a dozen lines of notices like this one: /.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

I have installed the mime gem. Hasn't changed the situation. What's next?

**Comment by johnnyshields** [comment]
This is fixed as of version 0.4.2

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#118
