### ISSUE TITLE
calling 'message' on email object returns 'wrong number of arguments (1 for 0 )

### ISSUE THREAD

**Issue by shawnbro** [nu7hatch/gmail#125]
Any idea why?

Here is the block:

`gmail.inbox.emails(:unread, from: sent_email.to_email).each do |inbox_email|
       puts "INBOX EMAIL: #{inbox_email.message}"
  end`

which throws this error:

ArgumentError: wrong number of arguments (1 for 0)
    from /Users/.../.rvm/gems/ruby-2.1.2/gems/gmail-0.4.2/lib/gmail/client/imap_extensions.rb:7:in `msg_att'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2210:in`numeric_response'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2152:in `response_untagged'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2132:in`response'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:2058:in `parse'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1181:in`get_response'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1089:in `receive_responses'
    from /Users/.../.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/imap.rb:1075:in`block in initialize'

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#125
