### ISSUE TITLE
Drop support for EOL Ruby

### ISSUE THREAD

**Issue by bootstraponline** [nu7hatch/gmail#128]
I suggest dropping support for Ruby 1.9.3 because it's [EOL soon](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/). If someone is on 1.9 then they can use the old version of the gem.

https://github.com/nu7hatch/gmail/pull/122

**Comment by johnnyshields** [comment]
We can make 0.5.x the last series to support 1.9.3

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#128
