### ISSUE TITLE
Run tests on Travis

### ISSUE THREAD

**Issue by bootstraponline** [nu7hatch/gmail#129]
Tests are kind of limited if they're not run automatically in CI. Travis has the ability to [encrypt credentials](http://docs.travis-ci.com/user/encryption-keys/) which would enable the gmail specs to run automatically.

**Comment by johnnyshields** [comment]
I've merged in my earlier PR which includes Travis support. Travis encryption is not ideal since it doesn't work with Pull Requests.

**Comment by bootstraponline** [comment]
sounds good. :+1:

**Comment by bootstraponline** [comment]
I think the integration hook isn't setup because there are no builds on travis.

https://travis-ci.org/nu7hatch/gmail

**Comment by johnnyshields** [comment]
We need @nu7hatch to setup Travis since it requires repo owner permission, and he's hard to track down. I've raised #131 to move to a new repo which we maintain, if all are agreed will do soon.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#129
