### ISSUE TITLE
Move gem to new location gmailgem/gmail

### ISSUE THREAD

**Issue by johnnyshields** [nu7hatch/gmail#131]
I've registered organization "gmailgem". If it's ok with everyone let's move the repo to gmailgem/gmail and make that official. Among reasons for doing this is that things like Travis CI require approval from @nu7hatch, there's bound to be more things in the future so easiest just to move the gem. Any comments? @jgrevich @webcracy @nu7hatch

**Comment by bootstraponline** [comment]
I agree, let's move to gmailgem.

**Comment by jcarbo** [comment]
@johnnyshields first of all this is awesome! Thanks for all the work merging all those PRs into the new repo.

@johnnyshields @bootstraponline @webcracy who owns the /gmailgem/gmail repo? Can you [enable issues on that fork](http://programmers.stackexchange.com/a/179470) so that we can use that as the main repo?

**Comment by johnnyshields** [comment]
@jcarbo I've contacted Github to see if they can migrate the issues over to the new repo. If not we can do so manually. Have also enabled you as a collaborator for gmailgem group.

**Comment by johnnyshields** [comment]
@jcarbo so, since none of us are admins (aside from @nu7hatch) on this repo we cannot transfer. I've enabled issue tracking on that repo.

It would be helpful if someone could attempt to copy issues from nu7hatch via the Github API to the new repo (see API docs here: https://developer.github.com/v3/issues/). It would be good as people often search issues for answers.

I will look into merging the remaining pull requests in the next week. It looks like they can be easily merged. Then we can close down this repo and put a "moved" message in the README.

**Comment by bootstraponline** [comment]
can someone make me a collaborator on this repo? I can't close the issues that I'm migrating.

**Comment by johnnyshields** [comment]
@bootstraponline I'll take care of closing them. Thanks so much for migrating.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#131

**Comment by bootstraponline** [comment]
All the issues should be fully migrated, thanks to @johnnyshields for helping.
