### ISSUE TITLE
weird require order dependence with awesome_print

### ISSUE THREAD

**Issue by yebyen** [nu7hatch/gmail#132]
For some reason I have to `require 'ap'` before I `require 'gmail'` — I think this order dependence is a bug of the gmail gem, but I don't even know where to start to look.  My gemfile.lock does not even mention activesupport, so I'm double confused why I would get this type of error.

Gemfile:
```
source 'https://rubygems.org'
gem 'gmail', :git => 'git://github.com/nu7hatch/gmail'
gem 'awesome_print', :require => 'ap'
```

test.rb:
```
#!/usr/bin/env ruby
require 'gmail'
require 'ap'
```

`bundle exec ./test.rb`:
```
/home/kbarrett/.rvm/gems/ruby-2.2.0/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `<top (required)>': undefined method `on_load' for ActiveSupport:Module (NoMethodError)
	from /home/kbarrett/.rvm/gems/ruby-2.2.0/gems/awesome_print-1.6.1/lib/ap.rb:10:in `require'
	from /home/kbarrett/.rvm/gems/ruby-2.2.0/gems/awesome_print-1.6.1/lib/ap.rb:10:in `<top (required)>'
	from ./test.rb:3:in `require'
	from ./test.rb:3:in `<main>'
```

If I switch the order of the require statements it's fine:

test.rb:
```
#!/usr/bin/env ruby
require 'ap'
require 'gmail'
```
(no crash)

**Comment by johnnyshields** [comment]
My guess is that Gmail is requiring a lib which defines ActiveSupport as a constant but doesn't actually load it.

In https://github.com/nu7hatch/gmail/blob/master/lib/gmail.rb you can see these requires:

```
require 'net/imap'
require 'net/smtp'
require 'mail'
require 'date'
require 'time'
```

Mail in particular looks suspect, see requires here: https://github.com/mikel/mail/blob/master/lib/mail.rb

So... to summarize, see if you get the same result with 'mail' gem by itself, and if so, close this issue and file it with mail here: https://github.com/mikel/mail

**Comment by johnnyshields** [comment]
FYI this may be related: https://github.com/mikel/mail/issues/574

**Comment by yebyen** [comment]
Thanks!  That's it exactly.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#132

**Comment by moshebeeri** [comment]
Weird issue, just moved the required line to top

**Comment by gerrywastaken** [comment]
I believe Mail 2.6.4 fixed this issue: https://github.com/mikel/mail/pull/830#discussion-diff-45785453L394

**Comment by thbar** [comment]
I can confirm upgrading mail to 2.6.4 also solved that issue for me (not using gmail but mail directly - yet in case it helps someone here!).
