### ISSUE TITLE
email#message undefined method

### ISSUE THREAD

**Issue by jShaf** [nu7hatch/gmail#2]
I could run this: 

> gmail.inbox.emails(:unread).each {|e| p e.subject}

but not this:

> gmail.inbox.emails(:unread).each {|e| p e.message}
> NoMethodError: undefined method `message' for #Mail::Message:0x00000102cdc578

Good work, btw!

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#2
