### ISSUE TITLE
Track some emails

### ISSUE THREAD

**Issue by VizirAdmin** [nu7hatch/gmail#25]
Hi,

I'm using gmail gem to send emails and I need track these emails. How can I do this?

I'm trying search the email with the message_id, but it bring all emails from my inbox and I want just the responses of a specific email.

Here is my actual code:

<pre>
    #save email with the message_id
    ...
    mail = gmail.deliver(email)
    Email.create(:message_id => mail.message_id, :from => user.email,
      :to => annotation.to, :body => annotation.content, :title => annotation.title,
      :annotation => annotation, :user => user)
</pre>

<pre>
    #search the mails with message_id
    messages = gmail.inbox.mails(:message_id => email.message_id)
</pre>

Regards,

Fabrício Ferrari de Campos

**Comment by johnnyshields** [comment]
Closing issue as it is 4 years old.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#25
