### ISSUE TITLE
Envelope (only header)

### ISSUE THREAD

**Issue by rkumar** [nu7hatch/gmail#3]
I am writing an ncurses client using gmail gem. Some issues:
1. When i fetch :all or :unread, the unread status in gmail is changed to read. How  to avoid this, since i have only displayed subject to user.

After searching I found that fetching ENVELOPE lets me see headers without resetting UNREAD status. Also, this is fast, compared to normal method. But gmail gem does not support ENVELOPE.

```
imap.fetch(message_id, "ENVELOPE")[0].attr["ENVELOPE"] 
```

I would like fetch body only when user clicks on mail, and only then should mail be changed to READ on gmail.

Look forward to your comments.
1. If i retrieve :all, is there any flag to check for UNREAD. Currently i have to retrieve them in 2 loops, so i can show user which are UNSEEN.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#3
