### ISSUE TITLE
Couldn't login to given GMail account: user@gmail.com

### ISSUE THREAD

**Issue by webdevotion** [nu7hatch/gmail#30]
Every once and a while ( local dev machine ) I run into this problem.
No idea what is causing it.

```bash
Couldn't login to given GMail account: user@gmail.com
```

My code running in a controller:

```ruby
    begin
      logger.info("log in")
      gmail = Gmail.connect!('user@gmail.com','44444444444')
      @emails = gmail.inbox.find(:from => "*@domain.tld", :after => Date.parse("2011-07-10")).reverse
    rescue Exception => exc
      logger.error("could not get to the emails: #{exc.message}")
    ensure
      
    end
```

I would be more than happy to provide more debug information.

* Ruby 1.8.7 p 352
* Ruby On Rails 2.3.8
* Using RVM

```bash

gem list gmail

*** LOCAL GEMS ***

gmail (0.4.0)
gmail_xoauth (0.3.0)
```

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#30

**Comment by ryannealmes** [comment]
I had this same issue and it seems google blocks any non google applications. You have to enable un-secure applications - such as this gem.

To fix go to https://myaccount.google.com/security and update your security settings to 'Allow less secure apps: ON'

After checking the documentation again, it actually tells you to do this there! Shows I should read more documentation.

Hope that helps.
