### ISSUE TITLE
undefined method `save_attachments_to' for Gmail::Message

### ISSUE THREAD

**Issue by webdevotion** [nu7hatch/gmail#31]
I'm not able to save attachments:

```ruby
unless email.attachments.empty?
  folder = "/public/system/files/"
  begin
    email.save_attachments_to( folder )
  rescue Exception => exc
    logger.error( exc.message )
  ensure
end
```

error message
```undefined method `save_attachments_to' for #<Gmail::Message0x123 mailbox=INBOX uid=124222>
```

Also tried going through each attachment and save them using
```attachment.save_to_file( location )
```

but it also results in `undefined method save_to_file`

**Comment by johnnyshields** [comment]
This is now corrected in the readme and answers are in this thread, hence closing.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#31
