### ISSUE TITLE
'Net::IMAP::BadResponseError'  >>> unknown command

### ISSUE THREAD

**Issue by syntaxTerr0r** [nu7hatch/gmail#36]
This error occurs randomly while using the lib.

The exact problem is well described here : http://stackoverflow.com/questions/6385276/unknown-command-on-gmail-gem

I'm trying to get my emails using the Gmail gem (source) with the next call:

```ruby
class MyClass
  def initialize account, credentials
    @gmail = Gmail.connect(account, credentials)
  end

  def get_attachments received_at, options
    mails = @gmail.inbox.find(
      :to => options[:to],
      :has=>:attachments,
      :before => options[:end_date],
      :after => received_at
     )
     #more code
   end
end
```

@gmail is a valid instance of Gmail class, and this call raises sometimes the next error:

_Unknown command v2if4084974eef.9_

The command (v2if4084974eef.9) changes in every call I make.

What am I doing wrong?

I'm using ruby-1.9.2-p180 and rails 3.1.0

**Comment by zgana** [comment]
I encountered this problem.  To get vmail working, I had to go to myaccount.google.com -> "connected apps & sites", and turn "Allow less secure apps" to "ON" (near the bottom of the page).  I guess vmail is less secure. XD

Hope this helps!

**Comment by johnnygoodman** [comment]
Pasting this above your Gmail.new command will make it work.

```
  # Monkey Patch
  # https://github.com/gmailgem/gmail/issues/228
  class Object
    def to_imap_date
      date = respond_to?(:utc) ? utc.to_s : to_s
      Date.parse(date).strftime('%d-%b-%Y')
    end
  end
```
