### ISSUE TITLE
find(:attachment) > returns "can't dup NilClass"

### ISSUE THREAD

**Issue by syntaxTerr0r** [nu7hatch/gmail#37]
If I do : 

```ruby
@gmail.mailbox(@boxname).emails(:attachment)
```

I get a TypeError : can't dup NilClass 

But if I do :

```ruby
@gmail.mailbox(@boxname).emails(:unread)
```
Everything works fine... Any idea ?

Thanks.

**Comment by johnnyshields** [comment]
Closing issue. Please re-open if @diazruy's answer doesn't work.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#37
