### ISSUE TITLE
Is there a way to retreive sent emails ? 

### ISSUE THREAD

**Issue by slash4** [nu7hatch/gmail#38]
hello, 

I need to do something, that I couldnt find until now. Is it possible to gather "sent" emails from Gmail ? I'm trying to reproduce the "is:sent" filter in standard Gmail search. 

I've tried many things, like mailbox('sent'), gmail.sent.mails, mailbox('is:sent')... And if we search as usual : gmail.inbox.search("doe"), it doesnt fetch the sent mail.

Thanks a lot, 

Alex

**Comment by johnnyshields** [comment]
Believe the issues in this thread are now fixed with PRs recently merged to master, hence closing. Please re-open or file a separate issue if you're still having problems.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#38
