### ISSUE TITLE
Gmail::Message has hard coded label names

### ISSUE THREAD

**Issue by github0013** [nu7hatch/gmail#41]
gmail has its own special label names such as

 "[Gmail]/All Mail",
 "[Gmail]/Drafts",
 "[Gmail]/Important",
 "[Gmail]/Sent Mail",
 "[Gmail]/Spam",
 "[Gmail]/Starred",
 "[Gmail]/Trash"

but these are translated in other language if the gmail language setting is not English.

For an instance, if I set it to Japanese, the labels are listed as below.
*the labels you create will not be affected under in any language setting

 "[Gmail]/すべてのメール",
 "[Gmail]/ゴミ箱",
 "[Gmail]/スター付き",
 "[Gmail]/下書き",
 "[Gmail]/迷惑メール",
 "[Gmail]/送信済みメール",
 "[Gmail]/重要"

I am currently using gmail in English to avoid this problem, but could there be a way to add a method to configure this language setting?

**Comment by johnnyshields** [comment]
#82 now merged hence closing,

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#41
