### ISSUE TITLE
NoMethodError: undefined method `stringify_keys!' 

### ISSUE THREAD

**Issue by danijel** [nu7hatch/gmail#42]
Hello, I have this problem popping up when I try to get message body.
I was able to track it down to message method in message.rb 
def message
      @message ||= Mail.new(@gmail.mailbox(@mailbox.name) {
        @gmail.conn.uid_fetch(uid, "RFC822")[0].attr["RFC822"] # RFC822
  })
end

It looks like Mail.new is throwing this error.
fetch returns message body string and Mail.new throws the error.
Any ideas?

Btw. I'm running this on rails 2.3.10, I have these gems installed

mail (2.3.0, 2.2.5)
mime (0.1)
mime-types (1.16)

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#42
