### ISSUE TITLE
Gmail Message ID

### ISSUE THREAD

**Issue by jnarowski** [nu7hatch/gmail#43]
Do you ever plan to add support for searching by message_id? This is not the email thread id, but the the Gmail frontend message id of the message (this is a 64-bit hexadecimal value, different from the RFC 822 Message-ID).

This is provided to Google Apps and contextual gadgets, and the message can be retrieved using this ID as follows:
http://code.google.com/apis/gmail/imap/#x-gm-msgid

I am not sure if the Ruby IMAP library supports it or what would be necessary to add it, but if this could be added that would be awesome.

**Comment by johnnyshields** [comment]
I've merged in the 90seconds fork, hence closing this issue.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#43
