### ISSUE TITLE
Best way to read the message.body

### ISSUE THREAD

**Issue by miguelgraz** [nu7hatch/gmail#44]
Hi, I recently used the gem and needed to interpret the real text of the message, I could do it with this code:

gmail.inbox.find(:unread).each do |mail|
  bod = mail.message.body.to_s
end

Is this the best way to do get the message text or I made a workaround?

Tks and congrats for the gem =)

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#44
