### ISSUE TITLE
possible race condition in emails()

### ISSUE THREAD

**Issue by rkumar** [nu7hatch/gmail#6]
I have one thread checking for count of unread emails in INBOX, another one is calling emails for all emails. I think the data is getting mixed.

The situation is that i use a thread to check unread counts for all labels (so that application is not held up). In the meantime, user fetches mails for Inbox. It appears that 2 concurrent calls for messages of one label, cause data inconsistency. 

Perhaps this is an application issue, but i thought i would just point it out to you.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#6
