### ISSUE TITLE
Move email back to Inbox

### ISSUE THREAD

**Issue by ksnyder** [nu7hatch/gmail#63]
Anyone know how to move an email back to the Gmail inbox with this gem (or with Net:IMAP)?  We successfully move emails out of the Inbox by copying them to another mailbox, then setting the 'delete' flag on the copy in the Inbox.  We'd like the user to be able to revert tagging errors, but when we reverse the steps and tell Gmail via IMAP to copy the email from a user-created mailbox back into the Inbox, it does not work -- we get a success flag, but the email does not show up in the Inbox, even after it is deleted from the user-created mailbox so that it has no tags on it.  Suggestions welcome!

**Comment by johnnyshields** [comment]
I believe this is just a matter of setting the appropriate label (Inbox) on the message. Closing issue as it is very old.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#63
