### ISSUE TITLE
Retrieving new messages since last connection

### ISSUE THREAD

**Issue by zenzei** [nu7hatch/gmail#64]
Is there anyway to recover only new mail since the last connection, using for example the last UID message read? I understand it should be easy but i don't know how to do it.

Thanks in advance

**Comment by johnnyshields** [comment]
FYI we have added the X-GM-MSGID on master. Also, the way I do this is to mark messages as archived which I've already read, and then only fetch the unarchived messages (this of course won't work for all use cases). Closing for now; please file a separate issue if there is a concrete follow-up to implement.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#64
