### ISSUE TITLE
Could this be used for non GMail accounts?

### ISSUE THREAD

**Issue by jmuheim** [nu7hatch/gmail#67]
Hello!

I have to write an email importer that connects to an IMAP account, then gets all unread email, create a new object out of every email, and then sets the emails to "read".

I tried the Mail gem, which seems nice, but it hasn't built-in support for flagging emails as read. So I stumbled over your GMail gem, which seems to use a lot of functionality of the Mail gem.

I'm a bit unsure now whether I should try to add the missed functionality to Mail myself, or whether your GMail gem could be what I need. So - is it possible to use it for other servers than GMail? And why do you think the Mail gem doesn't support so many features that your GMail gem does? Would it be hard to implement those features?

Thank you for your opinion,
Josh

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#67
