### ISSUE TITLE
What is the best way to handle emails periodically ? loops / eventmachine

### ISSUE THREAD

**Issue by cubiic** [nu7hatch/gmail#69]
Hi,

I was wondering that if I want the client to keep checking periodically new e-mails , what is the best way to achieve that ? simply to use a loop to do so https://gist.github.com/15a72402911368920903 ? or you recommend using eventmachine to do such a task . 

One more question please, anyone got the chance to check out how many client can be run in parallel and if there limitations for that ? 

I assume that the code could be modified to work with different type of clients as well if i'm not mistaken . 

Thanks in advance

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#69
