### ISSUE TITLE
determining starred emails in a mailbox

### ISSUE THREAD

**Issue by rkumar** [nu7hatch/gmail#7]
Am i missing some simple way of knowing which emails are starred so i can display accordingly.

So I retrieved those with label "[GMAIL]/Starred" and put their UID's in an array, so i could match UIDs with those in INBOX. However, the same email has a different UID in Starred Label and INBOX label !!!

(I starred the email on the web gmail interface, so i know its the same email).

I am sorry if i am spamming you with these queries since they are not relating to your gem. Any thoughts/tips would be welcome.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#7
