### ISSUE TITLE
encoding problem for foreign accents (spanish)

### ISSUE THREAD

**Issue by neohunter** [nu7hatch/gmail#70]
Hi,

I Have a problem with all the emails written in spanish with the characters à è ì ò ù, ñ, etc, it appears as the "?" symbol. What I can do to support that characters?

**Comment by johnnyshields** [comment]
I believe the issue here is due to the Mail gem, not Gmail. Please raise issue there if you're still experiencing it.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#70
