### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by pahnin** [nu7hatch/gmail#71]
I'm getting this message when I try to install using rake install

no such file to load -- ore/tasks
Run `gem install ore-tasks` to install 'ore/tasks'.
no such file to load -- metric_fu
Run `gem install metric_fu` to install Metric-Fu
WARNING: 'require 'rake/rdoctask'' is deprecated.  Please use 'require 'rdoc/task' (in RDoc 2.4.2+)' instead.
    at /var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/rdoctask.rb
rake aborted!
Don't know how to build task 'install'

I have installed 'ore' but still the same error, and coudnt install metric_fu because of some dependency error

**Comment by johnnyshields** [comment]
This issue looks like from a long time ago, hence closing

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#71
