### ISSUE TITLE
Request: include support for OAuth 2.0

### ISSUE THREAD

**Issue by ianmargolis** [nu7hatch/gmail#72]
Now that gmail_xoauth 0.4 supports Oauth2.0, is it possible to update this gem to allow for XOAuth2 authentication? Currently the gem is only configured for XOauth authentication.

If this is not going to occur in the foreseeable future, is anyone aware of a workaround that allows you to use the functionality of the gmail gem once successfully authenticated with IMAP Oauth 2.0 using the gmail_xoauth gem? Here is how I am currently authenticating with gmail_xoauth:

require 'gmail_xoauth'
imap = Net::IMAP.new('imap.gmail.com', 993, usessl = true, certs = nil, verify = false)
imap.authenticate('XOAUTH2', 'myemail@gmail.com', my_oauth2_token)

**Comment by johnnyshields** [comment]
This has been added to master, please give it a try.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#72

**Comment by PranayPant** [comment]
Hi,

I've been searching for a way to use Gmail.connect() in a way that works with xoauth2, but I haven't been able to get it to work.

For xoauth, the syntax is 
gmail = Gmail.connect(:xoauth, "email@domain.com", 
  :token           => 'TOKEN',
  :secret          => 'TOKEN_SECRET',
  :consumer_key    => 'CONSUMER_KEY',
  :consumer_secret => 'CONSUMER_SECRET'
)

For xoauth2, I tried gmail = Gmail.connect(:xoauth2, "test@gmail.com", :oauth2_token => "12345"), but I get a Net::IMAP::BadResponse error when I do gmail.inbox.count.

Is there a way to use Gmail.connect( ... ) to get this to work, or do I need to use other means?

Thanks,

**Comment by johnnyshields** [comment]
This gem is out of date, can you please check http://github.com/gmailgem/gmail
