### ISSUE TITLE
message.delete_label!(xxx) doesn't seem to work

### ISSUE THREAD

**Issue by wakiki** [nu7hatch/gmail#73]
Hi all,

I'm finding that I can add labels easily enough using message.label!("test")

but then message.delete_label!("test") doesn't seem to remove the label.

I note that labels are applied to converations in gmail rather than individual messages - I wonder if that is the problem, though it doesn't work even when there is only one message in the conversation.

I've checked the implementation in the source and it seems to just move the message back into all mail folder so not entirely sure how to fix this.

Is anyone else having this problem?

Steve

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#73
