### ISSUE TITLE
Never logs in, never errors out

### ISSUE THREAD

**Issue by XULRunner42** [nu7hatch/gmail#74]
I was trying a more complex oauth example, until I realized that wasn't my problem...

```
Gmail.connect!('kingdon@tuesdaystudios.com', 'DUHPASSWORD') do |gmail|

  puts gmail.logged_in?
  puts "test succeeded!"
end

puts "test succeeded?"
```

Always prints the second line, and never the first line, so it's not executing the block...

So I tried

```
gmail=Gmail.connect!('kingdon@tuesdaystudios.com', 'DUHPASSWORD')

  puts gmail.logged_in?
```

and it _always_ returns false.  I checked my password.  I checked network.  I'm using the latest every gem and ruby, `bundle update` and `rvm get head; rvm upgrade 1.9.3`

I have tried both `.connect` and `.connect!` so I expected I would see an error raised when the (whatever) failed, but no error is raised and the block never gets executed.  Any idea?

**Comment by johnnyshields** [comment]
I've added the following note to the readme. Please raise a PR if you think anything else should be added. Closing this issue.

```
## Troubleshooting

If you are having trouble connecting to Gmail:
* Please ensure your account is verified
* In [Gmail Security Settings](https://www.google.com/settings/security), enable access for less secure applications.
```

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#74
