### ISSUE TITLE
NameError: uninitialized constant GmailImapExtensions::T_LPAR 

### ISSUE THREAD

**Issue by joost** [nu7hatch/gmail#78]
I get the following error when reading emails:
```
NameError: uninitialized constant GmailImapExtensions::T_LPAR
```

It seems this constant is not defined anywhere at all?

**Comment by johnnyshields** [comment]
I think this is now fixed on master, hence closing

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#78
