### ISSUE TITLE
MANY features broken with Gmail's new "Gmail and Search field Trial

### ISSUE THREAD

**Issue by atrain0789** [nu7hatch/gmail#79]
I opted into Gmail's new "Gmail and Search" field trial a few days ago and now anytime I try to move a message to another mailbox, or remove a label, it adds the label, but then immediately moves it to the trash.  It does not remove the old label, and any attempt using the gem to remove the trash label or the original label using 'remove_label!' does not work.  I know this may not be pertinent now, but if this is a sign that Google is changing their API, it may very much affect this gem.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#79
