### ISSUE TITLE
email.delete! moves to All Mail instead of Trash

### ISSUE THREAD

**Issue by jerodsanto** [nu7hatch/gmail#8]
Just tested email.delete! and it flags as deleted, which Gmail seems to use to archive (All Mail) instead of delete (Trash).

I tried to work around this by adding the '[Gmail]/Trash" label and then flagging as deleted, but that seems to put it in the trash and leave it in the inbox. Very strange.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#8
