### ISSUE TITLE
Improperly processing labels containing parentheses

### ISSUE THREAD

**Issue by ryanlchan** [nu7hatch/gmail#81]
Gmail gem will crash when attempting to download a message's labels using the X-GM-LABELS extension when the labels contain a parenthesis (e.g. "Label (crashes)").

Error is cause by using Net::IMAP::ResponseParser#flag_list to load label data; Net::IMAP's FLAG_REGEXP improperly escapes parentheses, which causes the parser to crash.

Solution would be to create a set of dedicated functions to process labels based on the #flag_list model, but using a more inclusive regexp.

**Comment by johnnyshields** [comment]
PR #82 is now merged, hence closing.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#81
