### ISSUE TITLE
Get Email Label

### ISSUE THREAD

**Issue by pixelmultiplo** [nu7hatch/gmail#84]
Is it possible to get the labels associated with a Gmail::Message object?

I find a serious lack of documentation on how to handle single emails. Something like:

puts email.subject #prints the email subject

could be useful. I found out the most obvious by trial and error, some other by looking at the  source, but this does not make easy to get started. Thanks for your work.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#84
