### ISSUE TITLE
Message#label! raises Gmail::Message::NoLabelError when there's an existing label in different casing

### ISSUE THREAD

**Issue by stuliston** [nu7hatch/gmail#85]
Firstly, thanks for this gem. Your work has saved me a great deal of time.

I've spotted a bug in Message#label!

    def label!(name, from=nil)
      label(name, from) 
    rescue NoLabelError
      @gmail.labels.add(Net::IMAP.encode_utf7(name))
      label(name, from)
    end

When you try to add a label that already exists, but in a different case, you get a Gmail::Message::NoLabelError.

E.g.

    [15] pry> email.label!("example")
    => #<struct Net::IMAP::TaggedResponse
     tag="RUBY0060",
     name="OK"...

    [17] pry> email.label!("Example")
    Gmail::Message::NoLabelError: Label 'Example' doesn't exist! from /Users/stuliston/.rbenv/versions/1.9.3-p286-falcon/lib/ruby/gems/1.9.1/gems/gmail-0.4.0/lib/gmail/message.rb:103:in `rescue in label'

Depending on how you'd like this handled, I'd love to lend a hand in fixing it.

~ Stu

**Comment by johnnyshields** [comment]
It looks like this issue is behavior on the Gmail server side which we can't change? Perhaps PR #83 helps here? I'm closing this issue for now as it seems there are no follow-ups.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#85
