### ISSUE TITLE
Download all mails without attachment

### ISSUE THREAD

**Issue by vpoulain** [nu7hatch/gmail#86]
Hello ! 
First of all, thank you for this great job.
I want to download all mails from gmail to process them but it's very slow. For example I've done : 
    
			gmail = Gmail.connect("login","pass")
			mails = gmail.inbox.emails(:read)
			person = Hash.new(0)

			mails.each { |mail|
				// processing
			}

I thin it is very slow because I download mail with attachment ? Can I skip that ?
Thank you !

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#86
