### ISSUE TITLE
Problem with French characters as "é", "à", "è"....

### ISSUE THREAD

**Issue by bainf** [nu7hatch/gmail#89]
When listing mailboxes labels I'd errors due to special characters for example:
if the label is "INBOX" there is no problem, but errors shown when I had labels as "Archivés" or "Déplacement"

**Comment by johnnyshields** [comment]
@bainf this should now be fixed on master with PR #82. Please try it and reopen if still experiencing.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#89
