### ISSUE TITLE
Modifying Constants during SEARCH

### ISSUE THREAD

**Issue by bb** [nu7hatch/gmail#9]
Hi,

thanks for this Gem. It was a bit hard to find because you didn't fork from dcparker/ruby-gmail so it didn't appear in the Github Network view.
It's good to see someone is carrying this project on, because the other seems to be orphaned and has a lot of bugs which made me try this one.

And I found one here, too:
In https://github.com/nu7hatch/gmail/blob/master/lib/gmail/mailbox.rb#L35 you're getting the entries from MAILBOX_ALIASES and use them directly which makes the a second, less constrained search fail. The line should read:

```
    search = MAILBOX_ALIASES[args.shift].dup
```

You can confirm this with these lines:

```
puts gmail.mailbox("[Gmail]/Spam").emails.count
puts gmail.mailbox("[Gmail]/Spam").emails(:to => "*a*").count
puts gmail.mailbox("[Gmail]/Spam").emails.count
puts Gmail::Mailbox::MAILBOX_ALIASES.inspect
```

Assuming not all emails in the Spam folder contain an "a" in the recipient, the second number should be smaller and the third number should be equal to the first one again, which is not the case currently. You can also check the MAILBOX_ALIASES after a search which constrains something.

Thanks for your work!
Cheers,
Benjamin

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#9
