### ISSUE TITLE
How to search -label:somelabel

### ISSUE THREAD

**Issue by grossadamm** [nu7hatch/gmail#90]
I'm trying to search for emails that do not have a certain label. Typically in gmail you would search for `-label:somelabel`. I'm not sure how to accomplish the same thing here.

I've tried both of these without luck.

    gmail.inbox.find(:query => ["-label:#{environment}"]) # error: Could not parse command
    gmail.inbox.find({"-label" => environment}) # finds all emails not just those without the label

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#90
