### ISSUE TITLE
Searching Superstars

### ISSUE THREAD

**Issue by afomi** [nu7hatch/gmail#94]
Is it possible to search for Superstars like "red-bang"?  In Gmail, 'has:red-bang' works as an advanced search filter (https://support.google.com/mail/answer/7190).  I'm not sure if this is a .gem or API limitation.

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#94

**Comment by johnnyshields** [comment]
This should now be doable using gm: search option which exposes Gmail's native search interface via the X-GM-RAW flag.

**Comment by afomi** [comment]
Thanks for closing the loop on this.  I've tested that the `gm:` search option works for `has:attachment` and `is:starred`, but it still does not work with `has:red-bang`, so there appears to be a limitation on GMail's side about not supporting search for Superstars. It is not an issue for this .gem.

**Comment by johnnyshields** [comment]
@afomi FYI the repo has moved to https://github.com/gmailgem/gmail
