### ISSUE TITLE
Labels can be nested

### ISSUE THREAD

**Issue by kingdonb** [nu7hatch/gmail#99]
I have been using the gmail gem to help target clean up of my inbox labels and old mail, and I noticed that the only labels with slashes are the labels that start with [Gmail] -- eg. the built-in labels "Sent Mail" "Important" "All Mail"...

This means that two kinds of labels are not shown in my gmail.labels.all.map(&:to_s):

1) Labels that are nested (eg. create a label, "nest label under")
2) Labels that actually have slashes in their names (these are top-level IMAP folders but they have a slash in their name.  Sometimes Gmail transposes them into dashes for namespace consistency.)

I will try to figure out why and submit a pull request for this later.

**Comment by johnnyshields** [comment]
I've merged in PR #82 to master which may have fixed this. Please give it a look and re-open if needed. Closing issue for now.

**Comment by kingdonb** [comment]
Looks fixed to me, at least just looking superficially.

**Comment by johnnyshields** [comment]
This issue was moved to gmailgem/gmail#99
